upgraded rvm, bundler, rubygems-bundler

diff --git a/scripts/functions/utility b/scripts/functions/utility
--- a/scripts/functions/utility
+++ b/scripts/functions/utility
@@ -97,44 +97,6 @@ __rvm_ruby_string_paths_under()
   return 0
 }
 
-__rvm_quote_args()
-{
-  typeset quoted_string
-  quoted_string=""
-
-  for quoted_argument in "$@"
-  do
-    if printf "%b" "$quoted_argument" | \grep -v "^[[:alnum:]]$" >/dev/null
-    then
-      quoted_string="$quoted_string '$(printf "%b" "$quoted_argument" \
-        | \sed "s/'/\'\\\'\'/g")'" #"-fix display quotes
-    else
-      quoted_string="$quoted_string $quoted_argument"
-    fi
-  done
-
-  echo "$quoted_string" | \sed -e 's/^ *//g' -e 's/ *$//g'
-
-  return 0
-}
-
-__rvm_quote_args_with_shift()
-{
-  typeset shift_value
-  shift_value="$1"
-  shift
-
-  while [[ "$shift_value" -gt 0 && $# -gt 0 ]]
-  do
-    shift
-    ((shift_value--))
-  done
-
-  __rvm_quote_args "$@"
-  return 0
-}
-
-
 # Run a specified command and log it.
 __rvm_run()
 {
@@ -294,19 +256,74 @@ __rvm_add_to_path()
   builtin hash -r
 }
 
+is_parent_of()
+{
+  typeset name pid ppid pname
+  name=$1
+  pid=$2
+  while [[ -n "$pid" && "$pid" != "0" ]]
+  do
+    read ppid pname < <(ps -p $pid -o ppid= -o comm=)
+    if [[ -n "$ppid" && -n "$pname" ]]
+    then
+      if [[ "$pname" == "$name" ]]
+      then
+        echo $pid
+        return 0
+      else
+        pid=$ppid
+      fi
+    else
+      break
+    fi
+  done
+  return 1
+}
+
+rvm_is_a_shell_function()
+{
+  if (( ${rvm_is_not_a_shell_function:-0} > 0 )) && [[ "${1:-}" != "no_warning" ]]
+  then
+    if rvm_pretty_print stderr
+    then
+      printf "%b" "\n${rvm_notify_clr:-}RVM is not a function, selecting rubies with '${rvm_error_clr:-}rvm use ...${rvm_notify_clr:-}' will not work.${rvm_reset_clr:-}\n" >&2
+    else
+      printf "%b" "\nRVM is not a function, selecting rubies with 'rvm use ...' will not work.\n" >&2
+    fi
+    if is_parent_of gnome-terminal $$ >/dev/null
+    then
+      rvm_log "Please visit https://rvm.io/integration/gnome-terminal/ for a solution.\n" >&2
+    else
+      rvm_log "You need to change your terminal settings to allow shell login.
+Please visit https://rvm.io/workflow/screen/ for example.\n" >&2
+    fi
+  fi
+  return ${rvm_is_not_a_shell_function:-0}
+}
+
 __rvm_detect_xcode_version()
 {
   typeset version_file
-  version_file=/Developer/Applications/Xcode.app/Contents/version.plist
 
-  if [[ -f $version_file ]]
-  then
-    if [[ -x /usr/libexec/PlistBuddy ]]
+  for version_file in \
+    /Applications/Xcode.app/Contents/version.plist \
+    /Developer/Applications/Xcode.app/Contents/version.plist
+  do
+    if [[ -f $version_file ]]
     then
-      /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" $version_file
-    else
-      awk -F"[<>]" '/CFBundleShortVersionString/{ getline ; print $3 }' < $version_file
+      if [[ -x /usr/libexec/PlistBuddy ]]
+      then
+        /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" $version_file
+      else
+        sed -n '/<key>CFBundleShortVersionString<\/key>/{n; s/^.*>\(.*\)<.*$/\1/; p;}' < $version_file
+      fi
+      return 0
     fi
+  done
+
+  if builtin command -v xcodebuild >/dev/null
+  then
+    xcodebuild -version | sed -n '/Xcode/ {s/Xcode //; p;}'
   fi
 }
 
@@ -341,4 +358,26 @@ __rvm_version_compare()
     printf $3 | \awk -F. "{ printf ${transformer[*]} }";
     printf ' ]]'
   )"
+}
+
+__function_on_stack()
+{
+  typeset fun
+  for fun in "$@"
+  do
+    if [[ " ${FUNCNAME[*]} " =~ " $fun " ]]
+    then return 0
+    fi
+  done
+  return $#
+}
+
+__rvm_pager_or_cat_v()
+{
+  typeset -a _pager
+  if [[ -n "${PAGER:-}" ]]
+  then _pager=( "${PAGER}" )
+  else _pager=( "cat" "-v" )
+  fi
+  "${_pager[@]}" "$@"
 }
